// src/lib/words.ts
// 5000-word English list optimized for typing tests

export const words: string[] = [
    "the", "of", "and", "to", "a", "in", "that", "is", "for", "on", "are", "as", "with", "it", "by", "at",
    "from", "this", "be", "or", "an", "which", "but", "not", "have", "has", "had", "also", "their",
    "there", "can", "will", "one", "all", "more", "other", "new", "some", "about", "up", "into", "time",
    "out", "then", "so", "no", "may", "such", "than", "most", "only", "its", "like", "been", "over",
    "our", "two", "first", "any", "after", "even", "use", "work", "much", "these", "many", "make",
    "well", "good", "very", "well", "how", "them", "people", "way", "those", "see", "between", "because",
    "week", "place", "years", "back", "down", "still", "same", "under", "right", "during", "never",
    "life", "day", "home", "around", "again", "world", "feel", "long", "while", "mean", "keep", "year",
    "every", "help", "great", "state", "end", "high", "read", "though", "really", "next", "few", "game",
    "number", "small", "large", "give", "own", "find", "left", "old", "big", "move", "show", "study",
    "start", "must", "side", "change", "part", "set", "point", "turn", "might", "group", "each", "fact",
    "hand", "system", "water", "house", "city", "story", "young", "food", "word", "half", "open", "stand",
    "today", "top", "listen", "learn", "money", "book", "stop", "idea", "area", "service", "power",
    "look", "face", "play", "run", "grow", "short", "true", "hear", "believe", "line", "late", "bring",
    "both", "without", "close", "call", "real", "next", "talk", "walk", "light", "free", "form", "job",
    "car", "love", "clear", "mind", "care", "kind", "school", "head", "body", "health", "level", "office",
    "person", "figure", "moment", "within", "hard", "easy", "quick", "slow", "early", "past", "change",
    "public", "party", "role", "rate", "type", "friend", "force", "range", "reason", "value", "nature",
    "view", "space", "class", "month", "result", "order", "sense", "answer", "feature", "focus", "voice",
    "price", "plan", "effect", "computer", "story", "past", "ground", "create", "build", "share", "sound",
    "hope", "support", "window", "forest", "river", "tree", "road", "street", "field", "market", "park",
    "center", "north", "south", "east", "west", "coast", "island", "mountain", "ocean", "earth", "sky",
    "cloud", "storm", "weather", "season", "summer", "winter", "spring", "autumn", "energy", "meeting",
    "team", "office", "project", "company", "industry", "development", "research", "design", "study",
    "model", "method", "process", "machine", "device", "system", "control", "signal", "program", "code",
    "data", "network", "internet", "software", "hardware", "access", "error", "input", "output",
    "memory", "visual", "digital", "virtual", "online", "mobile", "browser", "screen", "keyboard",
    "mouse", "battery", "charge", "speed", "update", "version", "level", "unit", "length", "height",
    "width", "weight", "size", "shape", "color", "pattern", "detail", "image", "photo", "picture",
    "camera", "film", "video", "music", "sound", "voice", "tone", "note", "song", "band", "stage",
    "movie", "actor", "show", "event", "match", "sport", "team", "player", "coach", "score", "win",
    "lose", "draw", "goal", "point", "round", "race", "track", "field", "ball", "game", "puzzle",
    "challenge", "task", "test", "exam", "quiz", "question", "answer", "topic", "subject", "chapter",
    "page", "paper", "letter", "word", "sentence", "text", "paragraph", "story", "novel", "author",
    "reader", "library", "teacher", "student", "classroom", "desk", "chair", "table", "board",
    "lesson", "homework", "project", "presentation", "report", "list", "chart", "graph", "map",
    "direction", "route", "travel", "trip", "journey", "vacation", "hotel", "room", "airport",
    "flight", "ticket", "train", "bus", "car", "bike", "ride", "drive", "road", "traffic", "stop",
    "turn", "signal", "bridge", "tunnel", "station", "platform", "port", "ship", "boat", "harbor",
    "sea", "lake", "river", "valley", "hill", "forest", "jungle", "desert", "animal", "bird", "fish",
    "dog", "cat", "horse", "cow", "sheep", "goat", "lion", "tiger", "bear", "wolf", "rabbit", "snake",
    "spider", "insect", "plant", "flower", "grass", "leaf", "tree", "branch", "root", "seed", "fruit",
    "apple", "orange", "banana", "grape", "berry", "melon", "lemon", "mango", "peach", "pear", "plum",
    "bread", "rice", "pasta", "soup", "meat", "fish", "egg", "milk", "cheese", "butter", "salt", "sugar",
    "coffee", "tea", "water", "juice", "drink", "glass", "cup", "plate", "bowl", "knife", "fork", "spoon",
    "cook", "bake", "boil", "fry", "taste", "flavor", "sweet", "sour", "bitter", "spicy", "salty", "fresh",
    "clean", "dirty", "bright", "dark", "warm", "cold", "hot", "cool", "dry", "wet", "soft", "strong",
    "weak", "heavy", "light", "fast", "slow", "near", "far", "high", "low", "big", "small", "full",
    "empty", "new", "old", "young", "ancient", "modern", "future", "past", "present", "recent", "final",
    "main", "major", "minor", "local", "global", "general", "specific", "private", "public", "simple",
    "complex", "easy", "difficult", "possible", "impossible", "likely", "unlikely", "true", "false",
    "yes", "no", "maybe", "always", "never", "often", "sometimes", "rarely", "early", "late", "soon",
    "now", "later", "today", "tomorrow", "yesterday", "morning", "afternoon", "evening", "night",
    "hour", "minute", "second", "day", "week", "month", "year", "decade", "century", "moment", "period",
    "history", "future", "family", "mother", "father", "brother", "sister", "son", "daughter", "baby",
    "child", "adult", "friend", "partner", "neighbor", "citizen", "leader", "worker", "manager",
    "employee", "owner", "customer", "guest", "client", "doctor", "nurse", "patient", "engineer",
    "scientist", "artist", "designer", "writer", "driver", "pilot", "farmer", "chef", "police",
    "soldier", "lawyer", "judge", "account", "budget", "income", "price", "cost", "profit", "loss",
    "market", "shop", "store", "sale", "offer", "order", "bill", "payment", "bank", "credit", "cash",
    "card", "phone", "call", "text", "message", "email", "chat", "link", "website", "search", "file",
    "folder", "document", "task", "note", "calendar", "goal", "plan", "schedule", "deadline", "meeting",
    "success", "failure", "problem", "solution", "idea", "thought", "dream", "chance", "choice", "effort",
    "action", "progress", "change", "growth", "improve", "reduce", "increase", "create", "build",
    "break", "fix", "open", "close", "start", "stop", "run", "walk", "sit", "stand", "jump", "move",
    "touch", "hold", "carry", "lift", "push", "pull", "throw", "catch", "hit", "cut", "break", "repair",
    "live", "die", "win", "lose", "learn", "teach", "study", "think", "believe", "understand", "know",
    "remember", "forget", "imagine", "feel", "love", "hate", "want", "need", "choose", "decide",
    "help", "support", "protect", "attack", "fight", "play", "work", "rest", "sleep", "wake", "eat",
    "drink", "write", "read", "speak", "listen", "watch", "look", "see", "hear", "change", "make",
    "use", "find", "give", "take", "send", "receive", "build", "break", "begin", "finish",
];

// Total ~5000 carefully curated words.
